@host=https://localhost:7045
POST {{host}}/planes
Content-Type: application/json
{
	"motorName": "TesterMotor1",
	"type": "PassengerPlane",
	"power": 100100,
	"consumption": 11,
	"weightKg": 30001,
	"maxWeight": "60001",
	"name": "TesterFlyet1",
	"maxSpeed": "10000"
}