@host=https://localhost:7287
POST {{host}}/travels
Content-Type: application/json
{
	"PlaneId": "3e3794a6-f562-4b71-a6e4-202061e82403",
	"From": {
		"Latitude": 100,
		"Longitude": 100
	},
	"To": {
		"Latitude": 100.001,
		"Longitude": 100.001
	},
	"Employees": [
		"24ef6897-895a-4969-b45c-f480e66a9aca"
	],
	"Passengers": [
	],
	"TicketCost": 0,
	"WeightOfWeaponry": 600
}