@host=https://localhost:7287
POST {{host}}/travels
Content-Type: application/json
{
	"PlaneId": "0cdbb469-9440-45d4-812d-18a3618cd35d",
	"From": {
		"Latitude": 100,
		"Longitude": 100
	},
	"To": {
		"Latitude": 100.001,
		"Longitude": 100.001
	},
	"Employees": [
		"957cff99-b388-4ff7-a75e-62e187d4b261"
	],
	"Passengers": [
	],
	"TicketCost": 1000,
	"LaunchSpeed": 5000
}