@host=https://localhost:7287
POST {{host}}/travels
Content-Type: application/json
{
	"PlaneId": "5b8dabf9-84b0-4d86-9fa0-ce51f200d78b",
	"From": {
		"Latitude": 100,
		"Longitude": 100
	},
	"To": {
		"Latitude": 110,
		"Longitude": 110
	},
	"Employees": [
		"48be39be-bef9-44e3-ae3f-e279d9478bef"
	],
	"Passengers": [
	],
	"TicketCost": 1000,
	"LaunchSpeed": 5000
}