@host=https://localhost:7045
PUT {{host}}/planes
Content-Type: application/json
{
	"id": "657a7e03-e1d3-4af4-95c0-38ca60898956",
	"motorId": "accbac76-2f8a-41d9-8964-fa0d10ff2775",
	"motorName": "TesterMotor1",
	"type": "PassengerPlane",
	"power": 1001,
	"consumption": 11,
	"weightKg": 30001,
	"maxWeight": "60001",
	"name": "TesterFlyet1",
	"maxSpeed": "4001"
}