name: CI for All Projects

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - PlaneTest/PlaneApi/PlaneApi.csproj
          - PlaneTest/PeopleApi/PeopleApi.csproj
          - PlaneTest/TravelApi/TravelApi.csproj

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ${{ matrix.project }}

    - name: Build
      run: dotnet build ${{ matrix.project }} --configuration Release --no-restore

    - name: Test (PlaneTests only)
      if: matrix.project == 'PlaneTest/PlaneApi/PlaneApi.csproj'
      run: dotnet test PlaneTest/PlaneTests/PlaneTests.csproj --no-build --verbosity normal

    - name: Publish
      run: dotnet publish ${{ matrix.project }} --configuration Release --output ./artifacts/${{ matrix.project }}