name: CI for All Projects

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies 
        run: dotnet restore PlaneTest

      - name: Build 
        run: dotnet build PlaneTest --configuration Release --no-restore

      - name: Test 
        run: dotnet test PlaneTest --configuration Release --no-build